### PR TITLE
Fix mistake

### PR DESCRIPTION
**Pull request by lurr**
Sorry, but Krist, and by extension, Discord-Coin doesn't have a node system.

### CODE REVIEW

**Comment by Lleyton-Gray** [comment]
We consider it **Semi**-Decentralized because anyone can start their own 'variant' of Discord Coin, and people can choose which one they like. @joelcp3d made an honest mistake with the documentation, and I will merge this branch soon.

**Comment by lurr** [comment]
@Lleyton-Gray May I ask; what are you guys doing this for?
Is this some CC server or something?

**Comment by Lleyton-Gray** [comment]
A project for a cryptocurrency that works over [Discord](https://discordapp.com).

**Comment by Lleyton-Gray** [comment]
There might be a Discord bot for it also.

**Pull request merged**
